# Generated by Django 4.2.16 on 2024-12-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
