# Generated by Django 4.2.16 on 2024-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_rename_create_by_vacancy_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Повна зайнятість'), ('part', 'Неповна зайнятість')], max_length=20, null=True),
        ),
    ]
