# Generated by Django 4.2.16 on 2024-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='phone_number',
            field=models.CharField(default=80000000000, max_length=100),
            preserve_default=False,
        ),
    ]
