# Generated by Django 4.2.16 on 2024-12-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_vacancy_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(default='c@.d.com', max_length=254),
            preserve_default=False,
        ),
    ]
