# Generated by Django 4.2.16 on 2024-12-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0005_vacancy_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
