# Generated by Django 4.2.16 on 2024-12-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='resume',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ')], default='dp', max_length=2, verbose_name='Регіон'),
            preserve_default=False,
        ),
    ]
