# Generated by Django 4.2.16 on 2024-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_email_resume_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Повна зайнятість'), ('part', 'Неповна зайнятість')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.CharField(default='20 000 грн', max_length=100),
            preserve_default=False,
        ),
    ]
