# Generated by Django 4.2.16 on 2024-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ')], default='dp', max_length=2),
        ),
    ]
