# Generated by Django 4.2.16 on 2024-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_employment_type'),
        ('resume', '0004_resume_employment_type_resume_salary'),
        ('user', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_resumes',
            field=models.ManyToManyField(to='resume.resume'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_vacancies',
            field=models.ManyToManyField(to='vacancy.vacancy'),
        ),
    ]
