# Generated by Django 4.2.16 on 2024-12-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_employment_type_resume_salary'),
        ('vacancy', '0003_alter_vacancy_employment_type'),
        ('user', '0005_user_saved_resumes_user_saved_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_resumes',
            field=models.ManyToManyField(related_name='saved_by', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_vacancies',
            field=models.ManyToManyField(related_name='saved_by', to='vacancy.vacancy'),
        ),
    ]
