# Generated by Django 4.2.16 on 2024-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_company_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ')], default='dp', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ')], default='dp', max_length=2),
        ),
    ]
