# Generated by Django 4.2.16 on 2024-12-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_company_region_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ'), ('od', 'Одеса'), ('lv', 'Львів')], default='dp', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('dp', 'Дніпро'), ('kv', 'Київ'), ('od', 'Одеса'), ('lv', 'Львів')], default='dp', max_length=2),
        ),
    ]
